# Generated by Django 2.0.5 on 2019-09-23 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DietDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fooditem', models.CharField(max_length=100)),
                ('foodtimes', models.CharField(max_length=100)),
                ('foodtakenday', models.CharField(max_length=100)),
                ('takenduration', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PatientLoginDetails',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pwd', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='dietdetails',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patientapp.PatientLoginDetails'),
        ),
    ]
