# Generated by Django 2.0.5 on 2019-09-24 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dietdetails',
            name='email',
        ),
        migrations.DeleteModel(
            name='DietDetails',
        ),
        migrations.DeleteModel(
            name='PatientLoginDetails',
        ),
    ]
