# Generated by Django 2.0.5 on 2019-09-24 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patientapp', '0002_auto_20190924_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='DietDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('fooditem', models.CharField(max_length=100)),
                ('foodtimes', models.CharField(max_length=100)),
                ('foodtakenday', models.CharField(max_length=100)),
                ('takenduration', models.CharField(max_length=100)),
            ],
        ),
    ]
