# Generated by Django 2.0.5 on 2019-09-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0003_dietdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dietdetails',
            name='email',
            field=models.EmailField(max_length=100),
        ),
    ]
