# Generated by Django 2.0.5 on 2019-09-25 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patientapp', '0004_auto_20190925_0736'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DietDetails',
        ),
    ]
